#
# Closure build script
#
#

cmd: "java"
args:
- "-jar"
- "closure-compiler.jar"
- "--js_output_file=js/combinedJS.comb.js"
#- "--js_output_file=js/combinedLibs.comb.js"
- "js/defines.js"
- "js/src/*.js"
- "js/*.js"
- "!**.comb.js"
#- "!**Client.js"
cwd: "H:/SSHy"
